### ISSUE TITLE
Form enhancements

### ISSUE THREAD

**Issue by spicyfalafel** [Aidbox/viewdefinitions#46]
## Форма
- [x] добавить статический заголовок "View Definition" для формы как в фигме
- [x] добавить статический заголовок над таблицей Result 
- [x] третья иконка в табе - SQL (только для Aidbox) #42 
- [x] кнопки "Run" и "Save" и табы Form/YAML/SQL - в одну линию с заголовком (видимо переписывать компонент табов Ant на свой; https://ant.design/components/segmented) #41 
- [x] клик на таб YAML - показывать тоггл YAML/JSON, кнопку "скачать", и кнопку "copy" (внутри area как в gitbook) #26 
- [x] можно проверить - в табах убрать надписи YAML/Form/SQL, оставить только иконки
- [x] в редакторе monaco - добавить номера строк
- [x] новый селект должен быть раскрытым (#36)
- [ ] добавить линии строк на форме - еле заметные, но становится приятнее (не всей строке, чтоб не мешали вертикальным палочкам) #60 

![Image](https://github.com/Aidbox/viewdefinitions/assets/58147555/cbd6d210-c402-467e-b7a8-de0d60bf9493)
