### ISSUE TITLE
Next steps

### ISSUE THREAD

**Issue by spicyfalafel** [Aidbox/viewdefinitions#65]
1. Form page 
- [x] autocompletion of fhirpath #71 
- [x] eval ViewDefinition on Enter hit? (Ctrl+Enter) #92 
- [ ] user can create a blank ViewDefinition and choose a template (sample) #76 
- [ ] suggest to save ViewDefinition when leaving from VD Form #74 
- [x] drag and drop #73 
- [ ] undo & redo buttons and hotkey #94 
- [x] example tab (first resource) or structure like FHIR #89 

2. List of ViewDefinitions page
- [x] create an opinionated collection of VDs from SoF tests playground website which is good start point to understand possible ViewDefinitions #77
- [x] user can import VD from json/yaml (on +ViewDefinition button) #75

3. Data viewer page - basically clone of VANYA Viewer #18 
4. Settings page
~~- [ ] user can choose and configure:~~
 ~~- [ ] OAuth 2 credentials like VANYA viewer does~~
  ~~- [ ] URL to get data from db by sending view definition resource or created VD name (sof/eval-view rpc in Aidbox)~~ wait other FHIR servers 
~~- [ ] all user settings are saved in database and are not lost when the application is reloaded~~
~~- [ ] user has examples or documentation how to connect other FHIR servers (not Aidbox)~~

5. Authorization #29 
- [x] user can authorize by Google account
- [x] we know how many users try VD Designer and who they are

6. Publicity
- [x] VD Designer is deployed with url and SSL
- [ ] VD Designer repository is open-source
